CREATE TABLE order_item (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    quantity integer,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    
    FOREIGN KEY (order_id) REFERENCES "order" (id),
    FOREIGN KEY (product_id) REFERENCES product (id)   
);